[package]

name = "skia-bindings"
description = "Skia Bindings for Rust"
homepage = "https://github.com/rust-skia/rust-skia/skia-bindings"
repository = "https://github.com/rust-skia/rust-skia"
readme = "README.md"
keywords = ["skia", "rust-bindings", "vulkan", "opengl", "pdf"]
categories = ["external-ffi-bindings", "graphics", "multimedia::images", "rendering::graphics-api", "visualization"]
license = "MIT"

version = "0.27.3"
authors = ["LongYinan <lynweklm@gmail.com>", "Armin Sander <armin@replicator.org>"]
edition = "2018"
build = "build.rs"
links = "skia"
include = [ 
	"Cargo.toml", 
	"build.rs", 
	"build_support.rs", 
	"build_support/**/*.rs", 
	"src/**/*.h", 
	"src/**/*.cpp", 
	"src/defaults.rs", 
	"src/icu.rs", 
	"src/impls.rs",
	"src/lib.rs" ]

# Metadata used from inside the packaged crate that defines where to download skia and depot_tools archives from.
# Note: use short hashes here because of filesystem path size restrictions.
[package.metadata]
skia = "721f035"
depot_tools = "a110bf6"

[features]
default = []
gl = []
vulkan = []
metal = []
textlayout = []
# deprecated since 0.25.0
svg = []
shaper = ["textlayout"]

[dependencies]

[build-dependencies]
cc = "1.0.37"
# we'd like to reference specific bindgen versions here, because the generated
# bindings are platform dependent and critical to this project.
bindgen = "=0.53.2"
# For enum variant name replacements.
regex = "1.2.1"
heck = "0.3.1"

# for downloading and extracting prebuilt binaries and skia / depot_tools archives:
curl = "0.4.22"
flate2 = "1.0.7"
tar = "0.4.26"

# for reading .cargo.vcs_info.json to get the repository sha1 that is used to download
# the matching prebuilt binaries.
serde_json = "1.0.39"
# for reading Cargo.toml from within a package.
toml = "0.5.1"
